version: '2'
services:
  zookeeper:
    image: jwkoelewijn/zookeeper
    ports: 
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "9093"
      - "9094"
    links: 
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100/kafka-pep
      KAFKA_CREATE_TOPICS: "elections:3:3,votes:3:3,identity-access:3:3,identities:3:3,default:3:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
